version: '3'

services:
  mediawiki:
    build: ./Docker
    restart: always
    ports:
      - 80:80
    extra_hosts:
      - dockerhost:192.168.188.34
    depends_on:
      - mariadb
      - elasticsearch
    working_dir: /var/www/html
    volumes:
      - ./assets:/var/www/html/resources/assets
      # - ./LocalSettings.php:/var/www/html/LocalSettings.php
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mediawiki
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: single-node

volumes:
  mariadb_data:
  esdata: