version: '3'

services:
  mediawiki:
    build: ./Docker/Mediawiki
    restart: always
    ports:
      - 8001:80
    depends_on:
      - mariadb
      - fuseki
      - elasticsearch
    working_dir: /var/www/html
    links:
      - mariadb
  mariadb:
    build: ./Docker/MariaDb
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: mediawiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: single-node
  fuseki:
    command: [ "--update", "--loc", "databases/fuseki", "/fuseki" ]
    build: ./Docker/Fuseki
    image: fuseki
    ports:
      - 3030:3030
    volumes:
      - ./logs:/fuseki/logs
      - ./databases:/fuseki/databases

volumes:
  mariadb_data:
  esdata:
